### ISSUE TITLE
Compilation errors in scripts and missing prefabs in the Game scene

### ISSUE THREAD

**Issue by Sabih23** [matiasvallejosdev/game-europeancasinoroullete#1]
Hi,

Upon opening the project I am facing these errors.
![image](https://user-images.githubusercontent.com/33432528/150796973-5298ae91-9a03-4cff-8288-0bb3c6bbc1b1.png)

What is the cause of these?
Do I need to import a plugin ? If so then which one?

I have attached the log file for more details.
[Errors.txt](https://github.com/matiasvallejosdev/casino-roulette-game/files/7926088/Errors.txt)

Need your kind guidance. @matiasvallejosdev 
Thank you.

**Comment by mativallej** [comment]
Hi @Sabih23 !! 😄 💯 

**It is a pleasure that you are interested in the project!!!**

If you are sure you are running Unity 2020 or >.
_Another thing is that you put PORTRAIT on scene!_

I invite you to download the latest version of the repo through a pull.
Currently there were some conflicts that I just solved!

The issue was generated by .gitignore, which broke the Assembly dependencies, so the files were not correctly compiled.

Any questions ask me! Thanks!!!!!

**Comment by mativallej** [comment]
@Sabih23  Please you can run unit-testing and tell me if you have an error!

**Comment by matiasvallejosdev** [comment]
Hi!!!

Check the issue response on Github!

Thank you!!!!!! 🙂 🙂
________________________________
De: Sabih23 ***@***.***>
Enviado: lunes, 24 de enero de 2022 11:07
Para: matiasvallejosdev/casino-roulette-game ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [matiasvallejosdev/casino-roulette-game] Compilation errors in scripts and missing prefabs in the Game scene (Issue #1)


Hi,

Upon opening the project I am facing these errors.
[image]<https://user-images.githubusercontent.com/33432528/150796973-5298ae91-9a03-4cff-8288-0bb3c6bbc1b1.png>

What is the cause of these?
Do I need to import a plugin ? If so then which one?

I have attached the log file for more details.
Errors.txt<https://github.com/matiasvallejosdev/casino-roulette-game/files/7926088/Errors.txt>

Need your kind guidance.
Thank you.

**Comment by Sabih23** [comment]
@matiasvallejosdev  its working now. 
The project is really nice. Love your work.
I appreciate the prompt response. 
Thank you.
